# Generated by Django 4.0.6 on 2022-07-27 22:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_court_locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
