# Generated by Django 4.0.6 on 2022-07-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_court_locations', '0002_locations_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='location',
        ),
    ]
