# Generated by Django 4.0.6 on 2022-07-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_court_locations', '0004_publiccourts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiccourts',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='publiccourts',
            name='longitude',
        ),
    ]
