# Generated by Django 4.0.6 on 2022-07-30 19:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_court_locations', '0005_remove_publiccourts_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccourts',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
