# Generated by Django 4.0.6 on 2022-08-02 22:16

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_court_locations', '0006_publiccourts_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiccourts',
            name='location_address',
        ),
        migrations.AlterField(
            model_name='publiccourts',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
