# Generated by Django 4.0.6 on 2022-08-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_court_locations', '0007_remove_publiccourts_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccourts',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
