# Generated by Django 4.0.6 on 2022-08-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_court_locations', '0009_publiccourts_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccourts',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='publiccourts',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
